version: '3'
services:
  snmpb:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "161:161/udp"
      - "162:162/udp"
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XDG_RUNTIME_DIR=/tmp/runtime-root
      - LANG=C.UTF-8
      - LANGUAGE=C.UTF-8
      - LC_ALL=C.UTF-8
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - ./logs:/var/log/snmpb
      - ./tmp:/tmp
      - ./root:/root
    devices:
      # for your system, do ls /dev/dri and add accordingly
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    tty: true
    stdin_open: true
